version: '3.3'

volumes:
  food_data:
  front_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - food_data:/var/lib/postgresql/data/
  backend:
    image: mainer93/foodgram_backend
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ../data/ingredients.csv:/app/data/ingredients.csv
  frontend:
    image: mainer93/foodgram_frontend
    env_file: ../.env
    depends_on:
      - backend
    volumes:
      - front_data:/app/build/
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - 8000:80
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
      - front_data:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
